### ISSUE TITLE
I can't run 'GKNamesBookPlugin' plug-in built with make [bug]

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#19]
After I have built 'GKNamesBookPlugin' plug-in binaries, I couldn't use it.

GEDKeeper shows no GUI for the plug-in and the next text appears in the program's log:

> [11.05.2016 9:28:09] -> GK.ExExceptionHandler(): Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "GKNamesBookPlugin.NBResources.resources" was correctly embedded or linked into assembly "GKNamesBookPlugin" at compile time, or that all the satellite assemblies required are loadable and fully signed.
[11.05.2016 9:28:09] -> GK.ExExceptionHandler():    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at GKNamesBookPlugin.NamesBookWidget.PrepareList()
   at GKNamesBookPlugin.NamesBookWidget..ctor(Plugin plugin)
   at GKNamesBookPlugin.Plugin.Execute()
   at GKUI.MainWin.Plugin_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

After I had debugged the issue I've found out its source:
**File**: projects\GKNamesBookPlugin\NamesBookWidget.cs
**Code**:

```csharp
private void PrepareList()
{
    . . .
(1)    using (MemoryStream memStream = new MemoryStream(NBResources.book_names))
    . . .
```

Line (1) causes this exception:
> Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "GKNamesBookPlugin.NBResources.resources" was correctly embedded or linked into assembly "GKNamesBookPlugin" at compile time, or that all the satellite assemblies required are loadable and fully signed.

The problem is similar to one we had with GEDKeeper itself :smiling_imp:

**Comment by ruslangaripov** [comment]
Please assign 'bug' label to this ticket! Thx! :bug:
:smiling_imp:

**Comment by Serg-Norseman** [comment]
Tonight I will examine the issue with the resources in these subprojects.
