### ISSUE TITLE
Crash at startup

### ISSUE THREAD

**Issue by olivierberten** [Serg-Norseman/GEDKeeper#452]
Hi!

I'm on Ubuntu 22.10 and though GEDKeeper used to work fine, now it crashes right after startup.

Here's the crash report:
```
Gtk-Message: 23:17:08.869: Failed to load module "xapp-gtk3-module"
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
mono: ../../src/xcb_io.c :833 : _XRead:  l'assertion « !xcb_xlib_too_much_data_requested » a échoué.

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x55af9eef048e - /usr/bin/mono : (null)
	0x55af9ebe1c0e - /usr/bin/mono : (null)
	0x55af9ec15b1e - /usr/bin/mono : (null)
	0x7f22bfe3bcf0 - /lib/x86_64-linux-gnu/libc.so.6 : (null)
	0x7f22bfe9226b - /lib/x86_64-linux-gnu/libc.so.6 : pthread_kill
	0x7f22bfe3bc46 - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7f22bfe227fc - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x7f22bfe2271b - /lib/x86_64-linux-gnu/libc.so.6 : (null)
	0x7f22bfe33596 - /lib/x86_64-linux-gnu/libc.so.6 : (null)
	0x7f22bc302085 - /lib/x86_64-linux-gnu/libX11.so.6 : _XRead
	0x7f22bc3022c5 - /lib/x86_64-linux-gnu/libX11.so.6 : _XRead32
	0x7f22bc2e5e0c - /lib/x86_64-linux-gnu/libX11.so.6 : XListFontsWithInfo
	0x7f22bc33d0bc - /lib/x86_64-linux-gnu/libX11.so.6 : (null)
	0x7f22bc2f125f - /lib/x86_64-linux-gnu/libX11.so.6 : XCreateOC
	0x7f22bc2e6489 - /lib/x86_64-linux-gnu/libX11.so.6 : XCreateFontSet
	0x40391c17 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7f22afef76c0 from 0x7f22aec446c0
Pkilling 0x7f22b519f6c0 from 0x7f22aec446c0
Pkilling 0x7f22af6f66c0 from 0x7f22aec446c0
Pkilling 0x7f22ae18b6c0 from 0x7f22aec446c0
Pkilling 0x7f22add896c0 from 0x7f22aec446c0
Pkilling 0x7f22ad9876c0 from 0x7f22aec446c0
Pkilling 0x7f22ad1866c0 from 0x7f22aec446c0
Pkilling 0x7f22bc9ff6c0 from 0x7f22aec446c0
Pkilling 0x7f22ae38c6c0 from 0x7f22aec446c0
Pkilling 0x7f22adf8a6c0 from 0x7f22aec446c0
Pkilling 0x7f22c0014780 from 0x7f22aec446c0
Pkilling 0x7f22adb886c0 from 0x7f22aec446c0
Entering thread summarizer pause from 0x7f22aec446c0
Finished thread summarizer pause from 0x7f22aec446c0.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 4070487]
[New LWP 4070488]
[New LWP 4070503]
[New LWP 4070504]
[New LWP 4070505]
[New LWP 4070506]
[New LWP 4070507]
[New LWP 4070508]
[New LWP 4070509]
[New LWP 4070510]
[New LWP 4070518]
[New LWP 4070519]

This GDB supports auto-downloading debuginfo from the following URLs:
https://debuginfod.ubuntu.com 
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
futex_wait (private=0, expected=2, futex_word=0x55afa02d48d0) at ../sysdeps/nptl/futex-internal.h:146
146	../sysdeps/nptl/futex-internal.h: Aucun fichier ou dossier de ce type.
  Id   Target Id                                             Frame 
* 1    Thread 0x7f22c0014780 (LWP 4070486) "mono"            futex_wait (private=0, expected=2, futex_word=0x55afa02d48d0) at ../sysdeps/nptl/futex-internal.h:146
  2    Thread 0x7f22befff6c0 (LWP 4070487) "SGen worker"     __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55af9f056128) at ./nptl/futex-internal.c:57
  3    Thread 0x7f22bc9ff6c0 (LWP 4070488) "Finalizer"       __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55af9f055ea0) at ./nptl/futex-internal.c:57
  4    Thread 0x7f22aec446c0 (LWP 4070503) "mono"            0x00007f22bfee25e7 in __GI___wait4 (pid=4070532, stat_loc=0x7f22aec41c34, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
  5    Thread 0x7f22afef76c0 (LWP 4070504) "mono"            __futex_abstimed_wait_common64 (private=-184, cancel=true, abstime=0x7f22afef6c80, op=137, expected=0, futex_word=0x55af9f069408) at ./nptl/futex-internal.c:57
  6    Thread 0x7f22af6f66c0 (LWP 4070505) "Thread Pool Wor" __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22af6f5d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
  7    Thread 0x7f22ae38c6c0 (LWP 4070506) "Thread Pool Wor" __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ae38bd10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
  8    Thread 0x7f22ae18b6c0 (LWP 4070507) "Thread Pool Wor" __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ae18ad10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
  9    Thread 0x7f22adf8a6c0 (LWP 4070508) "Thread Pool Wor" __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22adf89d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
  10   Thread 0x7f22add896c0 (LWP 4070509) "Timer-Scheduler" __futex_abstimed_wait_common64 (private=163, cancel=true, abstime=0x7f22add88070, op=137, expected=0, futex_word=0x55afa005aa98) at ./nptl/futex-internal.c:57
  11   Thread 0x7f22adb886c0 (LWP 4070510) "Thread Pool I/O" 0x00007f22bff1112f in __GI___poll (fds=0x7f22980573a0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  12   Thread 0x7f22ad1866c0 (LWP 4070518) "Thread Pool Wor" __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ad185d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
  13   Thread 0x7f22ad9876c0 (LWP 4070519) "Thread Pool Wor" __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ad986d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57

Thread 13 (Thread 0x7f22ad9876c0 (LWP 4070519) "Thread Pool Wor"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ad986d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x7f22ad986d10, clockid=0, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f054cc8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f22ad986d10, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe98190 in do_futex_wait (sem=sem@entry=0x55af9f054cc8, abstime=abstime@entry=0x7f22ad986d10, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe9822b in __new_sem_wait_slow64 (sem=0x55af9f054cc8, abstime=0x7f22ad986d10, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee62257 in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 12 (Thread 0x7f22ad1866c0 (LWP 4070518) "Thread Pool Wor"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ad185d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x7f22ad185d10, clockid=0, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f054cc8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f22ad185d10, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe98190 in do_futex_wait (sem=sem@entry=0x55af9f054cc8, abstime=abstime@entry=0x7f22ad185d10, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe9822b in __new_sem_wait_slow64 (sem=0x55af9f054cc8, abstime=0x7f22ad185d10, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee62257 in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 11 (Thread 0x7f22adb886c0 (LWP 4070510) "Thread Pool I/O"):
#0  0x00007f22bff1112f in __GI___poll (fds=0x7f22980573a0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x000055af9ee00cd0 in  ()
#2  0x000055af9ee02fb5 in  ()
#3  0x000055af9edf7964 in  ()
#4  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#5  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 10 (Thread 0x7f22add896c0 (LWP 4070509) "Timer-Scheduler"):
#0  __futex_abstimed_wait_common64 (private=163, cancel=true, abstime=0x7f22add88070, op=137, expected=0, futex_word=0x55afa005aa98) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=163, abstime=0x7f22add88070, clockid=0, expected=0, futex_word=0x55afa005aa98) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55afa005aa98, expected=expected@entry=0, clockid=clockid@entry=1, abstime=abstime@entry=0x7f22add88070, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe8f7aa in __pthread_cond_wait_common (abstime=0x7f22add88070, clockid=1, mutex=0x55afa005aa48, cond=0x55afa005aa70) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_timedwait64 (cond=0x55afa005aa70, mutex=0x55afa005aa48, abstime=0x7f22add88070) at ./nptl/pthread_cond_wait.c:652
#5  0x000055af9eec52ee in  ()
#6  0x000055af9eee630e in  ()
#7  0x000055af9ee24ab1 in  ()
#8  0x000055af9eee5f62 in  ()
#9  0x000055af9ed8d4a5 in  ()
#10 0x00000000403d0f5f in  ()
#11 0x00007f22bf3de7a0 in  ()
#12 0x00007f22bf3de898 in  ()
#13 0x00007f22bf3de6d0 in  ()
#14 0x0000000000000000 in  ()

Thread 9 (Thread 0x7f22adf8a6c0 (LWP 4070508) "Thread Pool Wor"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22adf89d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x7f22adf89d10, clockid=0, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f054cc8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f22adf89d10, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe98190 in do_futex_wait (sem=sem@entry=0x55af9f054cc8, abstime=abstime@entry=0x7f22adf89d10, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe9822b in __new_sem_wait_slow64 (sem=0x55af9f054cc8, abstime=0x7f22adf89d10, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee62257 in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 8 (Thread 0x7f22ae18b6c0 (LWP 4070507) "Thread Pool Wor"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ae18ad10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x7f22ae18ad10, clockid=0, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f054cc8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f22ae18ad10, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe98190 in do_futex_wait (sem=sem@entry=0x55af9f054cc8, abstime=abstime@entry=0x7f22ae18ad10, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe9822b in __new_sem_wait_slow64 (sem=0x55af9f054cc8, abstime=0x7f22ae18ad10, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee62257 in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 7 (Thread 0x7f22ae38c6c0 (LWP 4070506) "Thread Pool Wor"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22ae38bd10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x7f22ae38bd10, clockid=0, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f054cc8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f22ae38bd10, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe98190 in do_futex_wait (sem=sem@entry=0x55af9f054cc8, abstime=abstime@entry=0x7f22ae38bd10, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe9822b in __new_sem_wait_slow64 (sem=0x55af9f054cc8, abstime=0x7f22ae38bd10, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee62257 in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 6 (Thread 0x7f22af6f66c0 (LWP 4070505) "Thread Pool Wor"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x7f22af6f5d10, op=393, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x7f22af6f5d10, clockid=0, expected=0, futex_word=0x55af9f054cc8) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f054cc8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x7f22af6f5d10, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe98190 in do_futex_wait (sem=sem@entry=0x55af9f054cc8, abstime=abstime@entry=0x7f22af6f5d10, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe9822b in __new_sem_wait_slow64 (sem=0x55af9f054cc8, abstime=0x7f22af6f5d10, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee62257 in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 5 (Thread 0x7f22afef76c0 (LWP 4070504) "mono"):
#0  __futex_abstimed_wait_common64 (private=-184, cancel=true, abstime=0x7f22afef6c80, op=137, expected=0, futex_word=0x55af9f069408) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=-184, abstime=0x7f22afef6c80, clockid=-1606751136, expected=0, futex_word=0x55af9f069408) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f069408, expected=expected@entry=0, clockid=clockid@entry=1, abstime=abstime@entry=0x7f22afef6c80, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe8f7aa in __pthread_cond_wait_common (abstime=0x7f22afef6c80, clockid=1, mutex=0x55af9f069420, cond=0x55af9f0693e0) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_timedwait64 (cond=0x55af9f0693e0, mutex=0x55af9f069420, abstime=0x7f22afef6c80) at ./nptl/pthread_cond_wait.c:652
#5  0x000055af9eec52ee in  ()
#6  0x000055af9eecd693 in  ()
#7  0x000055af9ee6315b in  ()
#8  0x000055af9edf7964 in  ()
#9  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#10 0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 4 (Thread 0x7f22aec446c0 (LWP 4070503) "mono"):
#0  0x00007f22bfee25e7 in __GI___wait4 (pid=4070532, stat_loc=0x7f22aec41c34, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
#1  0x000055af9eef08a6 in  ()
#2  0x000055af9ebe1c0e in  ()
#3  0x000055af9ec15b1e in  ()
#4  0x00007f22bfe3bcf0 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#5  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#6  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#7  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#8  0x00007f22bfe3bc46 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#9  0x00007f22bfe227fc in __GI_abort () at ./stdlib/abort.c:79
#10 0x00007f22bfe2271b in __assert_fail_base (fmt=0x7f22bf58f7d0 "%s%s%s :%u : %s%s l'assertion « %s » a échoué.\n%n", assertion=0x7f22bc376f70 "!xcb_xlib_too_much_data_requested", file=0x7f22bc376a14 "../../src/xcb_io.c", line=833, function=<optimized out>) at ./assert/assert.c:92
#11 0x00007f22bfe33596 in __GI___assert_fail (assertion=0x7f22bc376f70 "!xcb_xlib_too_much_data_requested", file=0x7f22bc376a14 "../../src/xcb_io.c", line=833, function=0x7f22bc3773b3 "_XRead") at ./assert/assert.c:101
#12 0x00007f22bc302085 in _XRead () at /lib/x86_64-linux-gnu/libX11.so.6
#13 0x00007f22bc3022c5 in _XRead32 () at /lib/x86_64-linux-gnu/libX11.so.6
#14 0x00007f22bc2e5e0c in XListFontsWithInfo () at /lib/x86_64-linux-gnu/libX11.so.6
#15 0x00007f22bc33d0bc in  () at /lib/x86_64-linux-gnu/libX11.so.6
#16 0x00007f22bc2f125f in XCreateOC () at /lib/x86_64-linux-gnu/libX11.so.6
#17 0x00007f22bc2e6489 in XCreateFontSet () at /lib/x86_64-linux-gnu/libX11.so.6
#18 0x0000000040391c17 in  ()
#19 0x0000000000000000 in  ()

Thread 3 (Thread 0x7f22bc9ff6c0 (LWP 4070488) "Finalizer"):
#0  __futex_abstimed_wait_common64 (private=<optimized out>, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55af9f055ea0) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=<optimized out>, abstime=0x0, clockid=0, expected=0, futex_word=0x55af9f055ea0) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f055ea0, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=<optimized out>) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe983af in do_futex_wait (sem=sem@entry=0x55af9f055ea0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:111
#4  0x00007f22bfe98440 in __new_sem_wait_slow64 (sem=0x55af9f055ea0, abstime=0x0, clockid=0) at ./nptl/sem_waitcommon.c:183
#5  0x000055af9ee581ce in  ()
#6  0x000055af9edf7964 in  ()
#7  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#8  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 2 (Thread 0x7f22befff6c0 (LWP 4070487) "SGen worker"):
#0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x55af9f056128) at ./nptl/futex-internal.c:57
#1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x55af9f056128) at ./nptl/futex-internal.c:87
#2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x55af9f056128, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
#3  0x00007f22bfe8f338 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55af9f056140, cond=0x55af9f056100) at ./nptl/pthread_cond_wait.c:503
#4  ___pthread_cond_wait (cond=0x55af9f056100, mutex=0x55af9f056140) at ./nptl/pthread_cond_wait.c:627
#5  0x000055af9eeab1fb in  ()
#6  0x00007f22bfe90402 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#7  0x00007f22bff1f590 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Thread 1 (Thread 0x7f22c0014780 (LWP 4070486) "mono"):
#0  futex_wait (private=0, expected=2, futex_word=0x55afa02d48d0) at ../sysdeps/nptl/futex-internal.h:146
#1  __GI___lll_lock_wait (futex=futex@entry=0x55afa02d48d0, private=0) at ./nptl/lowlevellock.c:49
#2  0x00007f22bfe92ab3 in __pthread_mutex_cond_lock (mutex=mutex@entry=0x55afa02d48d0) at ../nptl/pthread_mutex_lock.c:93
#3  0x00007f22bfe8f227 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55afa02d48d0, cond=0x55afa016b220) at ./nptl/pthread_cond_wait.c:616
#4  ___pthread_cond_wait (cond=0x55afa016b220, mutex=0x55afa02d48d0) at ./nptl/pthread_cond_wait.c:627
#5  0x00007f22bc308093 in _XReply () at /lib/x86_64-linux-gnu/libX11.so.6
#6  0x00007f22bc2fad52 in XQueryPointer () at /lib/x86_64-linux-gnu/libX11.so.6
#7  0x000000004046048b in  ()
#8  0x00007ffe77760708 in  ()
#9  0x00007ffe7776070c in  ()
#10 0x00007ffe77760638 in  ()
#11 0x000055afa00646e0 in  ()
#12 0x00007f2200000058 in  ()
#13 0x00007ffe77760714 in  ()
#14 0x00007ffe77760710 in  ()
#15 0x00007ffe77760640 in  ()
#16 0x00007ffe77760648 in  ()
#17 0x000000000600005a in  ()
#18 0x000055afa02f2eb0 in  ()
#19 0x0000000000000000 in  ()
[Inferior 1 (process 4070486) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f22bfe9226b):0x7f22bfe9225b  22 05 00 89 ea 89 de 89 c7 b8 ea 00 00 00 0f 05  "...............
0x7f22bfe9226b  41 89 c4 41 f7 dc 3d 00 f0 ff ff b8 00 00 00 00  A..A..=.........
0x7f22bfe9227b  44 0f 46 e0 e9 78 ff ff ff 0f 1f 40 00 4c 89 ef  D.F..x.....@.L..
0x7f22bfe9228b  e8 d0 a8 ff ff e9 33 ff ff ff 0f 1f 00 4c 89 ef  ......3......L..

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Windows.Forms.X11Keyboard:XCreateFontSet <0x000d6>
	  at System.Windows.Forms.X11Keyboard:CreateOverTheSpotXic <0x000e7>
	  at System.Windows.Forms.X11Keyboard:CreateXic <0x0011b>
	  at System.Windows.Forms.X11Keyboard:CreateXicForWindow <0x00053>
	  at System.Windows.Forms.X11Keyboard:FocusIn <0x000c3>
	  at System.Windows.Forms.XplatUIX11:SetFocus <0x000ef>
	  at System.Windows.Forms.XplatUI:SetFocus <0x0003c>
	  at System.Windows.Forms.ContainerControl:SendControlFocus <0x000bf>
	  at System.Windows.Forms.Form:SetVisibleCore <0x0087f>
	  at System.Windows.Forms.Control:set_Visible <0x0004b>
	  at System.Windows.Forms.Control:set_Visible <0x00083>
	  at System.Windows.Forms.Application:RunLoop <0x003df>
	  at System.Windows.Forms.Form:ShowDialog <0x00907>
	  at System.Windows.Forms.Form:ShowDialog <0x0002b>
	  at MessageBoxForm:RunDialog <0x0008f>
	  at MessageBoxForm:RunDialog <0x00073>
	  at System.Windows.Forms.MessageBox:Show <0x00077>
	  at GKUI.Platform.WFStdDialogs:ShowQuestionYN <0x0005f>
	  at GKCore.UpdateMan:WorkerMethod <0x00147>
	  at System.Threading.ThreadHelper:ThreadStart_Context <0x000ae>
	  at System.Threading.ExecutionContext:RunInternal <0x0018f>
	  at System.Threading.ExecutionContext:Run <0x00042>
	  at System.Threading.ExecutionContext:Run <0x0006d>
	  at System.Threading.ThreadHelper:ThreadStart <0x00042>
	  at System.Object:runtime_invoke_void__this__ <0x00091>
=================================================================
Abandon (core dumped)
```

**Comment by Serg-Norseman** [comment]
What version are you using?

Please wait a little, a few days. A new version of GEDKeeper specifically for Linux will be released soon, on a new basis.

**Comment by olivierberten** [comment]
I'm using the latest deb: 2.24.0-1

But I'll wait for v3 :-)

**Comment by Serg-Norseman** [comment]
GK v3.1.0 released.
