### ISSUE TITLE
Many issues with person’s pictures {bug}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#61]
**The first issue**: I can’t view new pictures instantly †. What I did:
1. Opened a person in editor window, for example, 'BLYTHE William Jefferson',
2. I clicked "Attach the portrait" button,
3. I added a new multimedia record (with PNG image and type "-" (however, type "Photo" doesn’t change anything)),
4. I clicked "Apply" in multimedia editor,
5. Person editor window appeared **but without my picture** †.
6. Okay. I closed the editor (with "Apply" or with "Cancel" (!) button) and opened it again.
7. Now I could see the picture in person editor window.

![gk-bug-5](https://cloud.githubusercontent.com/assets/16339987/18832067/c3426c06-8402-11e6-8f9e-77b0c7092469.png)

Please put your attention on the sixth step – even if I pressed "Cancel" button, the changes stored (see ticket #60 )! This is **the second issue**.

**The third issue** is also descended from the sixth step: if I added new photo in the person editor window and pressed "Cancel" button, such multimedia record does not appear on "Multimedia" record in the main window. If later I add new photo to any person and press "Apply" in person record window, both multimedia records appear on "Multimedia" record in the main window (_applied_ one and _canceled_ one).

**The fourth issue**: information about multimedia record remains visible after the last multimedia record has been removed ‡. See the screenshots below for details.

Before removing:

![gk-bug-before-remove](https://cloud.githubusercontent.com/assets/16339987/18832148/27819f48-8403-11e6-9247-86c76acb4ed1.png)

After removing:

![gk-bug-after-remove](https://cloud.githubusercontent.com/assets/16339987/18832152/2e3198c0-8403-11e6-9bd4-8de9d2fe2687.png)

It is worth noting that links on the information part of the window don’t do anything in such case.

**The fifth issue**: change confirmation text (see ticket #58 ) ‡.

![gk-bug-7](https://cloud.githubusercontent.com/assets/16339987/18832179/5508d7f6-8403-11e6-9d71-5fc1ad57a232.png)

**The sixth issue**: I can’t view an image. I see nothing after I clicked [View] link †.

![gk-bug-no-image](https://cloud.githubusercontent.com/assets/16339987/18832187/6536f4fa-8403-11e6-8b3d-041d04b2f308.png)

**The seventh issue**: A GUI object (window) for image is a **top** window (it's an object '2' on the previous screenshot). I can select it via Alt+Tab, for example, and see it on the taskbar. Is it by design?

† This problem relates only to releases of executable made by the 'make' tool, thus **outside Visual Studio environment**.

‡ Fixed by PR #68

**Comment by ruslangaripov** [comment]
> **The third issue** is also descended from the sixth step: if I added new photo in the person editor window and pressed "Cancel" button, such multimedia record does not appear on "Multimedia" record in the main window. If later I add new photo to any person and press "Apply" in person record window, both multimedia records appear on "Multimedia" record in the main window (*applied* one and *canceled* one).

I'm afraid this a "global" issue. For example, "Groups" tab has the same issue...

**Comment by ruslangaripov** [comment]
All problems in this issue, that relate to invisible picture, are an old bug.

@Serg-Norseman , do you remember you were fixing tickets #18, #19, #20? There was a problem with resources when GK executable was built by make (**i.e. outside VS environment**).

Invisible picture has the same origin I believe. Because if I build GK under VS, everything is fine. But this ticket was created basing on result of the 'make' utility. Therefore, if I make release from VS, everything is fine and all pictures are visible. But if I build GK with the 'make' tool, I get the following errors in GK log.

![gk-bug](https://cloud.githubusercontent.com/assets/16339987/18863517/1ae60b90-84ab-11e6-80dd-6ff08a4998ee.png)

Clicking "View" button writes this into the log:

> [27.09.2016 8:41:05] -> SearchManager.UpdateRecord(): The type initializer for 'Xapian.Xapian' threw an exception.
[27.09.2016 8:41:05] -> MediaViewerWin.SetFileRef(): Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "GKCommon.Controls.ExtResources.resources" was correctly embedded or linked into assembly "GKCommon" at compile time, or that all the satellite assemblies required are loadable and fully signed.

Clicking "Apply" button writes the following lines into the log:

> [27.09.2016 8:41:19] -> SearchManager.UpdateRecord(): The type initializer for 'Xapian.Xapian' threw an exception.
[27.09.2016 8:41:19] -> GK.ExExceptionHandler(): Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "GKCommon.Controls.ExtResources.resources" was correctly embedded or linked into assembly "GKCommon" at compile time, or that all the satellite assemblies required are loadable and fully signed.
[27.09.2016 8:41:19] -> GK.ExExceptionHandler():    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at GKCommon.Controls.ExtResources.get_iSizeToFit()
   at GKCommon.Controls.ImageView.InitializeComponent()
   at GKCommon.Controls.ImageView..ctor()
   at GKUI.Dialogs.PortraitSelectDlg.InitializeComponent()
   at GKUI.Dialogs.PortraitSelectDlg..ctor(IBaseWindow aBase)
   at GKUI.Dialogs.PersonEditDlg.btnPortraitAdd_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*I'll edit the topic to reveal this situation.*

**Comment by Serg-Norseman** [comment]
I think we need to generate resource files, as it does "msbuild" (append parameters for a namespace/class path of a resources).

**Comment by ruslangaripov** [comment]
> as it does "msbuild" (append parameters for a namespace/class path of a resources)

Do you have any documentation on this topic?

**Comment by Serg-Norseman** [comment]
I will try to look
